const numberFacts = [
  "0 is the coldest possible temperature old the Kelvin scale.",
  "1 is the loneliest number.",
  "2 is the price in cents per acre the USA bought Alaska from Russia.",
  "3 is the number of notes in a triad, the basic form of any chord.",
  "4 is the number of strings on a violin, a viola, a cello, double bass, a cuatro and a ukulele, and the number of string pairs on a mandolin.",
  "5 is the number of Korotkoff sounds when measuring blood pressure.",
  "6 is the number of points on a Star of David.",
  "7 is the approximate number of years in the lifespan of Irish Wolfhound dogs.",
  "8 is the number of legs that arachnids have.",
  "9 is the number of circles of Hell in Dante's Divine Comedy.",
  "10 is the average thickness of the Arctic ice sheet in feet.",
  "11 is the number of players in a field hockey team.",
  "12 is the number of pence in a shilling in the former British currency system.",
  "13 is the number of colonies that formed the United States.",
  "14 is the number of pieces the body of Osiris was torn into by his fratricidal brother Set.",
  "15 is the legal age for sexual intercourse in many countries.",
  "16 is the minimum age for getting an adult job in most states and provinces across the globe.",
  "17 is the number of syllables in a haiku (5+7+5).",
  "18 is the number of levels in hell in the Chinese mythos.",
  "19 is the final year a person is a teenager.",
  "20 is the number of ounces in Venti size coffees at Starbucks coffee shops.",
  "21 is the number of trump cards of the tarot deck if one does not consider The Fool to be a proper trump card.",
  "22 is the number of stars in the Paramount Films logo.",
  "23 is the number of crosses on Calvary in the Monty Python film Life Of Brian.",
  "24 is the number of books in the Tanakh.",
  "25 is the number of years of marriage marked in a silver wedding anniversary.",
  "26 is the number of letters in the Latin-derived English alphabet.",
  "27 is the number of bones in the human hand.",
  "28 is the number of Chinese constellations, \"Xiu\" or \"mansions\" (a literal translation), equivalent to the 12 western zodiac constellations.",
  "29 is the number of letters in the Turkish,Finnish, Swedish,Faroese,Danish and Norwegianalphabets.",
  "30 is the total number of major and minor keys in Western tonal music, including enharmonic equivalents.",
  "31 is the number of flavors of Baskin-Robbins ice cream.",
  "32 is the number of brains a leech has.",
  "33 is the temperature at which water boils according to the Newton scale.",
  "34 is the lucky number of Victor Pelevin's protagonist Stepan Mikhailov in the novel Numbers.",
  "35 is the basic film gauge in mm most commonly used for both analog photography and motion pictures.",
  "36 is the number of vehicles that run in each race of NASCAR's Camping World Truck Series.",
  "37 is the number of slots in European Roulette (numbered 0 through 36, the 00 is not used in European roulette as it is in American roulette).",
  "38 is the number of years it took the Israelites to travel from Kadesh Barnea to the Zered valley in Deuteronomy.",
  "39 is the number of signers to the United States Constitution, out of 55 members of the Philadelphia Convention delegates.",
  "40 is the number of positions on a number of radio countdown programs, most notably American Top 40 and American Country Countdown.",
  "41 is the number of soldiers in The Expendables (2010 film) tactor Eric Roberts laments to his subordinates about having been killed by star Sylvester Stallone in his escape from their island.",
  "42 is the sum of the codes of the letters in the words \"BIG BANG\" using the encoding A=1, B=2, C=3, etc.",
  "43 is the maximum number of cars participating in a NASCAR race in the Cup Series or Nationwide Series.",
  "44 is the percentage of kids who watch television before they go to sleep in the US.",
  "45 is the sapphire wedding anniversary in years of marriage.",
  "46 is the number of slices of pizza an average American kid eats in a year.",
  "47 is the number of phonemes in English phonology in Received Pronunciation.",
  "48 is the number of Ptolemaic constellations.",
  "49 is the number of days and night Siddhartha Gautama spent meditating as a holy man.",
  "50 is the traditional number of years in a jubilee period.",
  "51 is the atomic number of antimony.",
  "52 is the number of letters in the English alphabet, if majuscules are distinguished from minuscules.",
  "53 is the most points by a rookie in a NBA Playoff game (Philadelphia's Wilt Chamberlain, 1960).",
  "54 is the number of cards in a deck of playing cards, if two jokers are included.",
  "55 is the common speed limit for rural secondary roads and many urban freeways in many states of the United States.",
  "56 is the number of officially recognized ethnic groups in the list of ethnic groups in China.",
  "57 is the number of cm that the smallest man measured, Gul Mohammed (1957-1997) of India.",
  "58 is the minimum wind speed (mph) needed to issue a Severe Thunderstorm Warning.",
  "59 is the number corresponding to the last second in a given minute.",
  "60 is the number of seconds in a minute.",
  "61 is the number of points required to win a \"standard\" game of Cribbage.",
  "62 is the atomic number of samarium.",
  "63 is the number of chromosomes found in the offspring of a donkey and a horse.",
  "64 is number of codons in the RNA codon table under genetic code.",
  "65 is the traditional age for retirement in the United Kingdom, Germany and other countries.",
  "66 is the total number of chapters in the Bible book of Isaiah.",
  "67 is the number of counties in Florida.",
  "68 is the number of sectors on one cylinder of MFM hard disks with 4 heads and 17 sectors per track.",
  "69 is the atomic number of thulium, a lanthanide.",
  "70 is the number of years of marriage until the platinum wedding anniversary.",
  "71 is the atomic number of lutetium.",
  "72 is the average number of heartbeats per minute for a resting adult.",
  "73 is the percentage of girls in Bangladesh that are married by age 18.",
  "74 is the atomic number of tungsten.",
  "75 is the age limit for Canadian senators.",
  "76 is the atomic number of osmium.",
  "77 is the atomic number of iridium.",
  "78 is the number of lines that make up Metatron's Cube.",
  "79 is the record for cumulative weeks at #1 on the Billboard charts, held by Elvis Presley.",
  "80 is the length (years) of the Eighty Years' War (1568–1648).",
  "81 is the number of prayers said in the Rosary in each night.",
  "82 is the atomic number of lead.",
  "83 is the highest UHF channel on older televisions made before the late 1970s.",
  "84 is the code for international direct dial phone calls to Vietnam.",
  "85 is the atomic number of astatine.",
  "86 is the device number for a lockout relay function in electrical circuit protection schemes.",
  "87 is the number of tools in the Wenger Swiss Army Knife version XXL, listed in the Guinness Book of World Records as the world's most multi-functional penknife.",
  "88 is the pounds of oxygen that the adult human body requires daily.",
  "89 is the atomic number of actinium.",
  "90 is the latitude of the North Pole and the South Pole.",
  "91 is the amount of money one has if one has one coin of each U.S. denomination less than a dollar (penny, nickel, dime, quarter, half dollar) in cents.",
  "92 is the number of pounds of sugar the average American child consumes per year.",
  "93 is that approximate distance in millions of miles the Sun is away from the Earth.",
  "94 is the atomic number of plutonium.",
  "95 is the atomic number of americium.",
  "96 is the rating of Skyrim on metacritic.com.",
  "97 is the atomic number of berkelium.",
  "98 is the temperature (F) of the normal body.",
  "99 is a common price ending in psychological pricing."
]